DROP DATABASE IF EXISTS student_tracker;
CREATE SCHEMA student_tracker;
USE student_tracker;


DROP TABLE IF EXISTS ADDRESS;
CREATE TABLE ADDRESS
(
    ID           INT         NOT NULL AUTO_INCREMENT,
    STREET_NAME  VARCHAR(35) NOT NULL,
    HOUSE_NUMBER VARCHAR(10) NOT NULL,
    CITY_NAME    VARCHAR(25) NOT NULL,
    CITY_CODE    VARCHAR(5)  NOT NULL,
    COUNTRY_NAME VARCHAR(35) NOT NULL,
    PRIMARY KEY (ID)
#    CONSTRAINT FK_ADDRESS FOREIGN KEY (ID) REFERENCES STUDENT (ID) ON DELETE CASCADE
) AUTO_INCREMENT = 1
  DEFAULT CHARSET = latin1;

DROP TABLE IF EXISTS COURSE;
CREATE TABLE COURSE
(
    ID           INT          NOT NULL AUTO_INCREMENT,
    COURSE_TITLE VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY (COURSE_TITLE)
) AUTO_INCREMENT = 1
  DEFAULT CHARSET = latin1;

DROP TABLE IF EXISTS UNIVERSITY;
CREATE TABLE UNIVERSITY
(
    ID         INT          NOT NULL AUTO_INCREMENT,
    NAME       VARCHAR(100) NOT NULL,
    ADDRESS_ID INT          NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_UNIVERSITY_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID)
) AUTO_INCREMENT = 1
  DEFAULT CHARSET = latin1;

DROP TABLE IF EXISTS STUDENT;
CREATE TABLE STUDENT
(
    ID            INT          NOT NULL AUTO_INCREMENT,
    FIRST_NAME    VARCHAR(100) NOT NULL,
    LAST_NAME     VARCHAR(100) NOT NULL,
    EMAIL         VARCHAR(25)  NOT NULL,
    ADDRESS_ID    INT          NOT NULL,
    UNIVERSITY_ID INT          NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_STUDENT_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_STUDENT_UNIVERSITY FOREIGN KEY (UNIVERSITY_ID) REFERENCES UNIVERSITY (ID) ON DELETE CASCADE

) AUTO_INCREMENT = 1
  DEFAULT CHARSET = latin1;

DROP TABLE IF EXISTS BOOKED_COURSES;
CREATE TABLE BOOKED_COURSES
(
    STUDENT_ID INT NOT NULL,
    COURSE_ID  INT NOT NULL,
    CONSTRAINT PK_BOOKED_COURSES PRIMARY KEY (STUDENT_ID, COURSE_ID),
    CONSTRAINT FK_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (ID) ON DELETE NO ACTION,
    CONSTRAINT FK_COURSE FOREIGN KEY (COURSE_ID) REFERENCES COURSE (ID) ON DELETE NO ACTION
) DEFAULT CHARSET = latin1;





